version: '3.8'

services:
  nevent-client:
    image: vicn1708/nevent-client
    build: .
    container_name: nevent-client
    restart: always
    environment:
      - PORT=8080
    ports:
      - '8080:8080'
